housing:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: '/Users/andreamontes/Desktop/DataExpert/capstone-project-mamontesp/data/housing.duckdb'
      extensions:
        - httpfs
        - parquet